"""fix col

Revision ID: 013e9d54f287
Revises: a034a09c1c44
Create Date: 2022-06-16 17:09:57.397164

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '013e9d54f287'
down_revision = 'a034a09c1c44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mktcapmult', sa.Column('ev_to_sales_ratio', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mktcapmult', 'ev_to_sales_ratio')
    # ### end Alembic commands ###
