"""adding 11 tables

Revision ID: 51ff37eff531
Revises: bafb583ef511
Create Date: 2022-06-16 16:36:59.841267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51ff37eff531'
down_revision = 'bafb583ef511'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countrystats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('number_of_firms', sa.Integer(), nullable=False),
    sa.Column('sum_markcap_usd', sa.Float(), nullable=False),
    sa.Column('sum_total_debt_incl_leases_usd', sa.Float(), nullable=False),
    sa.Column('sum_firm_value_usd', sa.Float(), nullable=False),
    sa.Column('sum_usd', sa.Float(), nullable=False),
    sa.Column('sum_enterprise_value_usd', sa.Float(), nullable=False),
    sa.Column('median_current_pe', sa.Float(), nullable=False),
    sa.Column('median_trailing_pe', sa.Float(), nullable=False),
    sa.Column('median_forward_pe', sa.Float(), nullable=False),
    sa.Column('median_peg', sa.Float(), nullable=False),
    sa.Column('median_pbv', sa.Float(), nullable=False),
    sa.Column('median_ps', sa.Float(), nullable=False),
    sa.Column('median_cash_to_firm_value_pct', sa.Float(), nullable=False),
    sa.Column('median_ev_to_ebit', sa.Float(), nullable=False),
    sa.Column('median_ev_to_ebitda', sa.Float(), nullable=False),
    sa.Column('median_ev_to_invested_capital', sa.Float(), nullable=False),
    sa.Column('median_ev_to_sales', sa.Float(), nullable=False),
    sa.Column('median_payout_ratio_pct', sa.Float(), nullable=False),
    sa.Column('median_dividend_yield_pct', sa.Float(), nullable=False),
    sa.Column('median_hist_growth_net_income_last_5_years_pct', sa.Float(), nullable=False),
    sa.Column('median_hist_growth_revenues_last_5_years_pct', sa.Float(), nullable=False),
    sa.Column('median_exp_growth_rate_eps_next_5_years_pct', sa.Float(), nullable=False),
    sa.Column('median_exp_growth_revenues_next_2_years_pct', sa.Float(), nullable=False),
    sa.Column('median_return_on_equity_pct', sa.Float(), nullable=False),
    sa.Column('median_return_on_capital_pct', sa.Float(), nullable=False),
    sa.Column('median_net_profit_margin_pct', sa.Float(), nullable=False),
    sa.Column('median_pre_tax_operating_margin_pct', sa.Float(), nullable=False),
    sa.Column('median_effective_tax_rate_pct', sa.Float(), nullable=False),
    sa.Column('median_pct_held_by_institutions', sa.Float(), nullable=False),
    sa.Column('aggr_pe', sa.Float(), nullable=False),
    sa.Column('aggr_pbv', sa.Float(), nullable=False),
    sa.Column('aggr_ev_to_ebitda', sa.Float(), nullable=False),
    sa.Column('aggr_ev_to_invested_capital', sa.Float(), nullable=False),
    sa.Column('aggr_ev_to_sales', sa.Float(), nullable=False),
    sa.Column('agrr_roe_pct', sa.Float(), nullable=False),
    sa.Column('aggr_roc_pct', sa.Float(), nullable=False),
    sa.Column('aggr_net_margin_pct', sa.Float(), nullable=False),
    sa.Column('aggr_operating_margin_pct', sa.Float(), nullable=False),
    sa.Column('aggr_payout_ratio_pct', sa.Float(), nullable=False),
    sa.Column('aggr_dividend_yield', sa.Float(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('covideffects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('industry_name', sa.String(), nullable=False),
    sa.Column('number_of_firms', sa.Integer(), nullable=False),
    sa.Column('markcap_12_31_19_usd', sa.Float(), nullable=False),
    sa.Column('markcap_2_14_20_usd', sa.Float(), nullable=False),
    sa.Column('markcap_3_20_20_usd', sa.Float(), nullable=False),
    sa.Column('markcap_9_1_20_usd', sa.Float(), nullable=False),
    sa.Column('markcap_12_31_21_usd', sa.Float(), nullable=False),
    sa.Column('pct_chg_1_1_20_to_2_14_20', sa.Float(), nullable=False),
    sa.Column('pct_chg_2_14_20_to_3_20_20', sa.Float(), nullable=False),
    sa.Column('pct_chg_3_20_20_to_9_1_20', sa.Float(), nullable=False),
    sa.Column('pct_chg_9_1_20_to_12_31_21', sa.Float(), nullable=False),
    sa.Column('revenues_ltm_2020', sa.Float(), nullable=False),
    sa.Column('revenues_ltm_2021', sa.Float(), nullable=False),
    sa.Column('revenues_pct_chg', sa.Float(), nullable=False),
    sa.Column('op_income_ltm_20202', sa.Float(), nullable=False),
    sa.Column('op_income_ltm_20213', sa.Float(), nullable=False),
    sa.Column('op_income_pct_chg', sa.Float(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dollarus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('industry_name', sa.String(), nullable=False),
    sa.Column('number_of_firms', sa.Integer(), nullable=False),
    sa.Column('markcap_in_mil_usd', sa.Float(), nullable=False),
    sa.Column('book_equity_in_mil_usd', sa.Float(), nullable=False),
    sa.Column('enteprise_value_in_mil_usd', sa.Float(), nullable=False),
    sa.Column('invested_capital_in_mil_usd', sa.Float(), nullable=False),
    sa.Column('total_debt_including_leases_in_mil_usd', sa.Float(), nullable=False),
    sa.Column('revenues_in_mil_usd', sa.Float(), nullable=False),
    sa.Column('ebitda_in_mil_usd', sa.Float(), nullable=False),
    sa.Column('ebit_op_income_in_mil_usd', sa.Float(), nullable=False),
    sa.Column('net_income_in_mil_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eva',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('industry_name', sa.String(), nullable=False),
    sa.Column('number_of_firms', sa.Integer(), nullable=False),
    sa.Column('beta', sa.Float(), nullable=False),
    sa.Column('roe_pct', sa.Float(), nullable=False),
    sa.Column('cost_of_equity_coe_pct', sa.Float(), nullable=False),
    sa.Column('roe_minus_coe_pct', sa.Float(), nullable=False),
    sa.Column('bv_of_equity_usd', sa.Float(), nullable=False),
    sa.Column('equity_eva_in_mil_usd', sa.Float(), nullable=False),
    sa.Column('roc_pct', sa.Float(), nullable=False),
    sa.Column('cost_of_capital_pct', sa.Float(), nullable=False),
    sa.Column('roc_minus_wacc_pct', sa.Float(), nullable=False),
    sa.Column('bv_of_capital_usd', sa.Float(), nullable=False),
    sa.Column('eva_in_mil_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mktcapmult',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('markcap_decile', sa.String(), nullable=False),
    sa.Column('number_of_firms', sa.Integer(), nullable=False),
    sa.Column('pe', sa.Float(), nullable=False),
    sa.Column('pbv', sa.Float(), nullable=False),
    sa.Column('price_to_sales_ratio', sa.Float(), nullable=False),
    sa.Column('ev_to_ebit_ratio', sa.Float(), nullable=False),
    sa.Column('ev_to_ebitda_ratio', sa.Float(), nullable=False),
    sa.Column('ev_to_invested_capital_ratio', sa.Float(), nullable=False),
    sa.Column('roe_pct', sa.Float(), nullable=False),
    sa.Column('pre_tax_roic_pct', sa.Float(), nullable=False),
    sa.Column('price_sales_ratio', sa.Float(), nullable=False),
    sa.Column('net_margin_pct', sa.Float(), nullable=False),
    sa.Column('operating_margin_pct', sa.Float(), nullable=False),
    sa.Column('pct_companies_with_net_income_less_zero', sa.Float(), nullable=False),
    sa.Column('pct_companies_with_operating_income_less_zero', sa.Float(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mktcaprisk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('markcap_in_mil_usd', sa.String(), nullable=False),
    sa.Column('count_markcap_in_usd', sa.Integer(), nullable=False),
    sa.Column('aggregate_markcap_in_usd', sa.Float(), nullable=False),
    sa.Column('annual_roi_in_us_t_bond_percentage', sa.Float(), nullable=False),
    sa.Column('cash_to_firm_value_as_pct', sa.Float(), nullable=False),
    sa.Column('annual_trading_volume_to_shrs_oustanding_ratio', sa.Float(), nullable=False),
    sa.Column('markdebt_to_capital_ratio_median_as_pct', sa.Float(), nullable=False),
    sa.Column('median_beta', sa.Float(), nullable=False),
    sa.Column('correlation_with_markmedian', sa.Float(), nullable=False),
    sa.Column('std_in_stock_price_median_as_pct', sa.Float(), nullable=False),
    sa.Column('total_beta', sa.Float(), nullable=False),
    sa.Column('hil0_risk_measure_to_hi_plus_lo_median_ratio', sa.Float(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('optvar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('industry_name', sa.String(), nullable=False),
    sa.Column('number_of_firms', sa.Integer(), nullable=False),
    sa.Column('std_dev_equity_pct', sa.Float(), nullable=False),
    sa.Column('std_dev_firm_value_pct', sa.Float(), nullable=False),
    sa.Column('equity_divided_by_debt_plus_equity_pct', sa.Float(), nullable=False),
    sa.Column('debt_divided_bt_debt_plus_equity_pct', sa.Float(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pbvdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('industry_name', sa.String(), nullable=False),
    sa.Column('number_of_firms', sa.Integer(), nullable=False),
    sa.Column('pbv', sa.Float(), nullable=False),
    sa.Column('roe_pct', sa.Float(), nullable=False),
    sa.Column('ev_to_invested_capital_ratio', sa.Float(), nullable=False),
    sa.Column('roic_pct', sa.Float(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('industry_name', sa.String(), nullable=False),
    sa.Column('number_of_firms', sa.Integer(), nullable=False),
    sa.Column('current_pe', sa.Float(), nullable=False),
    sa.Column('trailing_pe', sa.Float(), nullable=False),
    sa.Column('forward_pe', sa.Float(), nullable=False),
    sa.Column('aggregate_markcap_to_net_income_ratio_all_firms', sa.Float(), nullable=False),
    sa.Column('aggregate_markcap_to_trailing_net_income_ratio_only_money_making_firms', sa.Float(), nullable=False),
    sa.Column('exp_eps_growth_5_years', sa.Float(), nullable=False),
    sa.Column('peg_ratio', sa.Float(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('psdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('industry_name', sa.String(), nullable=False),
    sa.Column('number_of_firms', sa.Integer(), nullable=False),
    sa.Column('price_sales_ratio', sa.Float(), nullable=False),
    sa.Column('net_margin_pct', sa.Float(), nullable=False),
    sa.Column('ev_sales_ratio', sa.Float(), nullable=False),
    sa.Column('pre_tax_operating_margin_pct', sa.Float(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vebitda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('industry_name', sa.String(), nullable=False),
    sa.Column('number_of_firms', sa.Integer(), nullable=False),
    sa.Column('positive_ebitda_firms_ev_to_ebitdar_d', sa.Float(), nullable=False),
    sa.Column('positive_ebitda_firms_ev_to_ebitda', sa.Float(), nullable=False),
    sa.Column('positive_ebitda_firms_ev_to_ebit', sa.Float(), nullable=False),
    sa.Column('positive_ebitda_firms_ev_to_ebit_1_minus_t', sa.Float(), nullable=False),
    sa.Column('all_firms_ev_to_ebitdar_d_2', sa.Float(), nullable=False),
    sa.Column('all_firms_ev_to_ebitda3', sa.Float(), nullable=False),
    sa.Column('all_firms_ev_to_ebit4', sa.Float(), nullable=False),
    sa.Column('all_firms_ev_to_ebit_1_minus_t_5', sa.Float(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vebitda')
    op.drop_table('psdata')
    op.drop_table('pedata')
    op.drop_table('pbvdata')
    op.drop_table('optvar')
    op.drop_table('mktcaprisk')
    op.drop_table('mktcapmult')
    op.drop_table('eva')
    op.drop_table('dollarus')
    op.drop_table('covideffects')
    op.drop_table('countrystats')
    # ### end Alembic commands ###
