"""removing additional column

Revision ID: a034a09c1c44
Revises: 51ff37eff531
Create Date: 2022-06-16 17:03:00.273899

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a034a09c1c44'
down_revision = '51ff37eff531'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mktcaprisk', 'annual_roi_in_us_t_bond_percentage')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedata', sa.Column('aggregate_markcap_to_trailing_net_income_ratio_only_money_makin', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('pedata', 'aggregate_markcap_to_trailing_net_income_ratio_only_money_making_firms')
    # ### end Alembic commands ###
