"""ref_industry_groups

Revision ID: c035b7e84ff1
Revises: 16198a509ed1
Create Date: 2022-02-27 10:22:16.150063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c035b7e84ff1'
down_revision = '16198a509ed1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ref_items_industry_name',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('exchange_ticker', sa.String(), nullable=False),
    sa.Column('industry_group', sa.String(), nullable=False),
    sa.Column('primary_sector', sa.String(), nullable=False),
    sa.Column('sic_code', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('broad_group', sa.String(), nullable=False),
    sa.Column('sub_group', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ref_items_industry_name')
    # ### end Alembic commands ###
